# Generated by Django 4.0.4 on 2022-05-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(choices=[('Institute 1', 'Institute 1'), ('Institute 2', 'Institute 2'), ('Institute 3', 'Institute 3'), ('Institute 4', 'Institute 4'), ('Institute 5', 'Institute 5'), ('Institute 6', 'Institute 6')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Computer-Human Interface', 'Computer-Human Interface'), ('Game Design', 'Game Design'), ('Networks and Security', 'Networks and Security'), ('Computer Graphics', 'Computer Graphics'), ('Data Science', 'Data Science'), ('Others', 'Others')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(max_length=255)),
                ('level', models.TextField(max_length=16)),
                ('year_of_passing', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.institute')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.skill')),
            ],
        ),
    ]
