# Generated by Django 4.0.4 on 2022-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_other_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_status',
            field=models.CharField(choices=[('PENDING', 'In Queue'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
