# Generated by Django 4.0.4 on 2022-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='candidates.skill'),
        ),
        migrations.DeleteModel(
            name='CandidateSkills',
        ),
    ]
