# Generated by Django 4.0.4 on 2022-05-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_skills_delete_candidateskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.institute'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.specialization'),
        ),
    ]
